baseURL = 'https://caseyjrobinson.com/'
languageCode = 'en-us'
title = 'casey j robinson'

theme = 're-terminal'

[params]
  themeColor = "red"
  contentTypeName = "posts"

[outputs]
  home    = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]

